title: Numbers instead of notes
hero_image: images/banner.png
description: Instructions on using frequency numbers instead of notes in MicroPython when using picozero.
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - 
    title: Numbers instead of notes
