
title: Des chiffres au lieu de notes
hero_image: images/banner.png
description: Instructions sur l'utilisation des numéros de fréquences au lieu des notes dans MicroPython lors de l'utilisation de picozero.
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title: Des chiffres au lieu de notes
